spring.application.name=contact-management-system

spring.datasource.url=jdbc:mysql://localhost:3306/contactmanagement
spring.datasource.username=root
spring.datasource.password=Akshat@1604
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
